-- AlterEnum
ALTER TYPE "JobStatus" RENAME VALUE 'PENDING' TO 'AWAITING_QUOTE';
ALTER TYPE "JobStatus" RENAME VALUE 'QUOTED' TO 'QUOTATION_SENT';
ALTER TYPE "JobStatus" RENAME VALUE 'IN_PROGRESS' TO 'REPAIRING';

-- Add new enum values
ALTER TYPE "JobStatus" ADD VALUE 'CANCELLED';